modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
issueTrackerURL="${mod_issues_tracker}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_display_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
credits="${mod_authors}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true 
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"