modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${mod_issues_tracker}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_display_name}"
    displayURL="${mod_homepage}"
    logoFile="logo.png"
    credits="${mod_authors}"
    authors="${mod_authors}"
    description='''
${mod_description}
'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[accessTransformers]]
    file = "META-INF/accesstransformer-common.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"